# Generated by Django 4.2.24 on 2025-09-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('ua', models.CharField(blank=True, max_length=400)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
